mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from mysite.views import hello, current_datetime, hours_ahead, contact#, display_meta
from books import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello),
    url(r'^time/$', current_datetime),
    url(r'^time/plus/(\d{1,2})/$', hours_ahead),
#    url(r'^meta/$', display_meta),
    url(r'^search/$', views.search),
    url(r'^contact/$', contact),
]

books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name = 'e-mail')

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

mysite/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from books.models import Book

# Create your views here.

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html',
                            {'books': books, 'query': q})
    return render(request, 'search_form.html', {'errors': errors})

mysite/views.py
from django.shortcuts import render
from mysite.forms import ContactForm
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
import datetime

def hello(request):
    return HttpResponse("Hello world")

def current_datetime(request):
    now = datetime.datetime.now()
    return render(request, 'current_datetime.html', {'current_date': now})

def hours_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404()
    dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
#    assert False   # uncomment to dump local variables into debugger
    return render(request, 'hours_ahead.html', {'hour_offset': offset,
                                                'next_time': dt})

def display_meta(request):
    values = list(request.META.items())   # object type dict_items is set-like
    values.sort()
    html = []
    for k, v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render(request, 'contact_form.html', {'form': form})

books/templates/search_form.html
<html>
<head>
	<title>Search</title>
</head>
<body>
	{% if errors %}
		<ul>
			{% for error in errors %}
			<li style="color: red;">{{ error }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	<form action="" method="get">
		<input type="text" name="q">
		<input type="submit" value="Search">
	</form>
</body>
</html>

books/templates/search_results.html
<html>
<head>
	<title>Book Search</title>
</head>
<body>
	<p>You searched for: <strong>{{ query }}</strong></p>

	{% if books %}
		<p>Found {{ books|length }} book{{ books|pluralize }}.</p>
		<ul>
			{% for book in books %}
			<li>{{ book.title }}</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No books matched your search criteria.</p>
	{% endif %}
</body>
</html>

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

<html lang="en">

<head>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<h1>My helpful timestamp site</h1>
	{% block content %}{% endblock %}

	{% block footer %}
	<hr>
	<p>Thanks for visiting my site.</p>
	{% endblock %}
</body>
</html>

templates/contact_form.html
<html>
<head>
	<title>Contact us</title>
	<style type="text/css">
		ul.errorlist {
			margin: 0;
			padding: 0;
		}
		.errorlist li {
			background-color: red;
			color: white;
			display: block;
			font-size: 10px;
			margin 0 0 3px;
			padding: 4px 5px;
		}
		.field_errors {
			color: purple;
		}
	</style>
</head>
<body>
	<h1>Contact us</h1>

	{% if form.errors %}
		<p style="color: red;">
			Please correct the error{{ form.errors|pluralize }} below.
		</p>
	{% endif %}

	<form action="" method="post">
		<div class="field">
			{{ form.subject.errors }}
			<label for="id_subject">Subject:</label>
			{{ form.subject }}
		</div>
		<div class="field">
			{{ form.email.errors }}
			<label for="id_email">Your e-mail address:</label>
			{{ form.email }}
		</div>
		<div class="field{% if form.message.errors %}_errors{% endif %}">
			{% if form.message.errors %}
				<ul>
				{% for error in form.message.errors %}
					<li><strong>{{ error }}</strong></li>
				{% endfor %}
				</ul>
			{% endif %}
			<label for="id_message">Message:</label>
			{{ form.message }}
		</div>
		{% csrf_token %}
		<input type="submit" value="Submit">
	</form>
</body>
</html>

templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
	<p>It is now {{ current_date }}.</p>
{% endblock %}

templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>
	In {{ hour_offset }} hour(s), it will be {{ next_time }}.
</p>
{% endblock %}